# Assignment No.2

## Dataset 1: Heart Attack Cases in Japan

In [48]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("japan_heartattack.csv")
# First, we drop the irrelevant columns
columns_to_drop = ['Extra_Column_1', 'Extra_Column_2', 'Extra_Column_3',
       'Extra_Column_4', 'Extra_Column_5', 'Extra_Column_6', 'Extra_Column_7',
       'Extra_Column_8', 'Extra_Column_9', 'Extra_Column_10',
       'Extra_Column_11', 'Extra_Column_12', 'Extra_Column_13',
       'Extra_Column_14', 'Extra_Column_15']
data = data.drop(columns = columns_to_drop)
data.columns

Index(['Age', 'Gender', 'Region', 'Smoking_History', 'Diabetes_History',
       'Hypertension_History', 'Cholesterol_Level', 'Physical_Activity',
       'Diet_Quality', 'Alcohol_Consumption', 'Stress_Levels', 'BMI',
       'Heart_Rate', 'Systolic_BP', 'Diastolic_BP', 'Family_History',
       'Heart_Attack_Occurrence'],
      dtype='object')

In [46]:
data.head(10)

,Age,Gender,Region,Smoking_History,Diabetes_History,Hypertension_History,Cholesterol_Level,Physical_Activity,Diet_Quality,Alcohol_Consumption,Stress_Levels,BMI,Heart_Rate,Systolic_BP,Diastolic_BP,Family_History,Heart_Attack_Occurrence
0,56,Male,Urban,Yes,No,No,186.400209,Moderate,Poor,Low,3.644786,33.961349,72.301534,123.902090,85.682809,No,No
1,69,Male,Urban,No,No,No,185.136747,Low,Good,Low,3.384056,28.242873,57.457640,129.893306,73.524262,Yes,No
2,46,Male,Rural,Yes,No,No,210.696611,Low,Average,Moderate,3.810911,27.601210,64.658697,145.654901,71.994812,No,No
3,32,Female,Urban,No,No,No,211.165478,Moderate,Good,High,6.014878,23.717291,55.131469,131.785220,68.211333,No,No
4,60,Female,Rural,No,No,No,223.814253,High,Good,High,6.806883,19.771578,76.667917,100.694559,92.902489,No,No
5,25,Female,Rural,No,No,No,220.340040,Low,Good,High,8.207233,20.247438,67.662676,134.596623,73.149703,No,No
6,78,Male,Urban,No,Yes,Yes,176.534859,High,Poor,High,4.594368,21.240765,60.065501,96.438421,91.102486,No,No
7,38,Female,Urban,Yes,No,No,203.443219,High,Poor,NaN,5.334899,14.979730,62.077527,138.127972,93.183468,No,No
8,56,Male,Rural,No,No,Yes,214.271573,Moderate,Average,Moderate,6.798660,31.300143,72.275592,150.746257,90.610518,No,Yes
9,75,Male,Urban,No,No,No,183.983885,Moderate,Good,Moderate,3.678722,18.212167,74.914387,105.661297,75.717444,Yes,No

### Question Number 1
Which is the greater indicator of heart attack? BMI or Heart_Rate?

### Psuedocode
1. Convert the target variable (`Heart_Attack_Occurrence`) into numerical format (0 = No, 1 = Yes)
2. Compute the correlation of BMI and Heart Rate with `Heart_Attack_Occurrence`
3. Calculate the mean and standard deviation of BMI and Heart Rate for people who had a heart attack and those who did not
4. Compare the correlation values and statistical differences to determine which feature is a stronger indicator
5. Return the feature with the stronger association

### Single Line

In [47]:
# Converting the target variable into 0 or 1

data["Heart_Attack_Occurrence"] = data["Heart_Attack_Occurrence"].map({"No": 0, "Yes": 1})

In [38]:
# Computing the Correlation of BMI and Heart_Rate with the target variable

correlation_bmi = data["BMI"].corr(data["Heart_Attack_Occurrence"])
correlation_hr = data["Heart_Rate"].corr(data["Heart_Attack_Occurrence"])
print(correlation_bmi, correlation_hr)

-0.00521511532636152 0.005483886973609107

In [39]:
# Compute mean and standard deviation for each category

bmi_stats = data.groupby("Heart_Attack_Occurrence")["BMI"].agg(["mean", "std"])
hr_stats = data.groupby("Heart_Attack_Occurrence")["Heart_Rate"].agg(["mean", "std"])

In [40]:
# Print correlation and statistical results

print(f"Correlation with Heart Attack Occurrence: BMI: {correlation_bmi} Heart Rate: {correlation_hr}")

Correlation with Heart Attack Occurrence: BMI: -0.00521511532636152 Heart Rate: 0.005483886973609107

In [41]:
# Return the stronger indicator
if abs(correlation_bmi) > abs(correlation_hr):
    print("BMI is a stronger indicator of heart attack.")
else:
    print("Heart Rate is a stronger indicator of heart attack.")

Heart Rate is a stronger indicator of heart attack.

### Function / Example Usage

In [50]:
def compare_heart_attack_indicators(data):
    data["Heart_Attack_Occurrence"] = data["Heart_Attack_Occurrence"].map({"No": 0, "Yes": 1})

    # Computing the correlations
    correlation_bmi = data["BMI"].corr(data["Heart_Attack_Occurrence"])
    correlation_hr = data["Heart_Rate"].corr(data["Heart_Attack_Occurrence"])

    # Computing the mean and standard deviation for each category
    bmi_stats = data.groupby("Heart_Attack_Occurrence")["BMI"].agg(["mean", "std"])
    hr_stats = data.groupby("Heart_Attack_Occurrence")["Heart_Rate"].agg(["mean", "std"])

    # Printing results
    print(f"Correlation with Heart Attack Occurrence: BMI: {correlation_bmi} Heart Rate: {correlation_hr}")

    # Returning the stronger indicator
    if abs(correlation_bmi) > abs(correlation_hr):
        print("BMI is a stronger indicator of heart attack.")
    else:
        print("Heart Rate is a stronger indicator of heart attack.")

#### Example Usage

In [51]:
compare_heart_attack_indicators(data)

Correlation with Heart Attack Occurrence: BMI: -0.00521511532636152 Heart Rate: 0.005483886973609107
Heart Rate is a stronger indicator of heart attack.

### Question Number 2
Among individuals who have experienced a heart attack, what are the trends in their physical activity levels, diet quality, and alcohol consumption?

### Psuedocode
1. Filter the dataset to include only rows where `Heart_Attack_Occurrence` is "Yes"
2. Compute the distribution of:
   - Physical activity levels
   - Diet quality
   - Alcohol consumption levels
3. Return the summary statistics and category counts for each factor

### Single Line

In [69]:
data2 = pd.read_csv('japan_heartattack.csv')
columns_to_drop = ['Extra_Column_1', 'Extra_Column_2', 'Extra_Column_3',
       'Extra_Column_4', 'Extra_Column_5', 'Extra_Column_6', 'Extra_Column_7',
       'Extra_Column_8', 'Extra_Column_9', 'Extra_Column_10',
       'Extra_Column_11', 'Extra_Column_12', 'Extra_Column_13',
       'Extra_Column_14', 'Extra_Column_15']
data2 = data2.drop(columns = columns_to_drop)
data2.head

<bound method NDFrame.head of        Age  Gender Region Smoking_History Diabetes_History  \
0       56    Male  Urban             Yes               No
1       69    Male  Urban              No               No
2       46    Male  Rural             Yes               No
3       32  Female  Urban              No               No
4       60  Female  Rural              No               No
...    ...     ...    ...             ...              ...
29995   68  Female  Urban              No               No
29996   69    Male  Urban              No              Yes
29997   23  Female  Rural              No               No
29998   45    Male  Rural              No               No
29999   45    Male  Urban              No               No

      Hypertension_History  Cholesterol_Level Physical_Activity Diet_Quality  \
0                       No         186.400209          Moderate         Poor
1                       No         185.136747               Low         Good
2                       No         210.696611               Low      Average
3                       No         211.165478          Moderate         Good
4                       No         223.814253              High         Good
...                    ...                ...               ...          ...
29995                   No         200.331218          Moderate      Average
29996                   No         211.305863               Low         Good
29997                   No         247.182956          Moderate      Average
29998                   No         222.262521               Low         Poor
29999                   No         253.135837          Moderate      Average

      Alcohol_Consumption  Stress_Levels        BMI  Heart_Rate  Systolic_BP  \
0                     Low       3.644786  33.961349   72.301534   123.902090
1                     Low       3.384056  28.242873   57.457640   129.893306
2                Moderate       3.810911  27.601210   64.658697   145.654901
3                    High       6.014878  23.717291   55.131469   131.785220
4                    High       6.806883  19.771578   76.667917   100.694559
...                   ...            ...        ...         ...          ...
29995                 Low       4.636488  25.187205   62.863074   103.427533
29996            Moderate       3.258175  27.432525   89.024263   122.130067
29997                High       5.930121  29.053131   83.672958   118.726793
29998                High       3.517361  32.847927   67.614209   134.028414
29999            Moderate       2.400179  21.435098   81.230593   110.296172

       Diastolic_BP Family_History Heart_Attack_Occurrence
0         85.682809             No                      No
1         73.524262            Yes                      No
2         71.994812             No                      No
3         68.211333             No                      No
4         92.902489             No                      No
...             ...            ...                     ...
29995     86.778317             No                      No
29996     88.516513             No                      No
29997     79.765509             No                      No
29998     84.330021            Yes                      No
29999     85.387186             No                      No

[30000 rows x 17 columns]>

In [71]:
# Filtering the dataset for only the individuals that had a heart attack

heart_attack = data2[data2["Heart_Attack_Occurrence"] == "Yes"]
heart_attack.head()

,Age,Gender,Region,Smoking_History,Diabetes_History,Hypertension_History,Cholesterol_Level,Physical_Activity,Diet_Quality,Alcohol_Consumption,Stress_Levels,BMI,Heart_Rate,Systolic_BP,Diastolic_BP,Family_History,Heart_Attack_Occurrence
8,56,Male,Rural,No,No,Yes,214.271573,Moderate,Average,Moderate,6.798660,31.300143,72.275592,150.746257,90.610518,No,Yes
32,75,Male,Urban,No,No,No,263.986469,Moderate,Average,High,4.569311,27.318179,68.196256,88.113584,92.602249,No,Yes
34,78,Female,Urban,No,No,Yes,189.362047,High,Average,Moderate,7.073536,28.428964,60.232660,111.987980,83.116908,No,Yes
35,61,Male,Urban,Yes,No,No,204.462973,Moderate,Good,NaN,6.211564,23.026736,63.987772,148.858694,83.499061,No,Yes
38,44,Male,Urban,No,Yes,No,226.983422,High,Good,Moderate,2.171330,39.244018,74.646547,84.619366,96.306117,Yes,Yes

In [145]:
# Computing the most frequent levels of physical activity, diet quality, and alcohol consumption
physical_activity_mode = heart_attack["Physical_Activity"].mode()
diet_quality_mode = heart_attack["Diet_Quality"].mode()
alcohol_consumption_mode = heart_attack["Alcohol_Consumption"].mode()

# Computing the proportion of each category
physical_activity_dist = heart_attack["Physical_Activity"].value_counts(normalize=True) * 100
diet_quality_dist = heart_attack["Diet_Quality"].value_counts(normalize=True) * 100
alcohol_consumption_dist = heart_attack["Alcohol_Consumption"].value_counts(normalize=True) * 100

In [146]:
print("Most Common Lifestyle Factors for Individuals Who Had a Heart Attack:")
print("- Physical Activity Mode:",physical_activity_mode)
print("- Diet Quality Mode:", diet_quality_mode)
print("- Alcohol Consumption Mode:", alcohol_consumption_mode)

print("Percentage Distribution of Each Factor:")
print("Physical Activity Distribution:", physical_activity_dist)
print("Diet Quality Distribution:", diet_quality_dist)
print("Alcohol Consumption Distribution:", alcohol_consumption_dist)

Most Common Lifestyle Factors for Individuals Who Had a Heart Attack:
- Physical Activity Mode: 0    Moderate
Name: Physical_Activity, dtype: object
- Diet Quality Mode: 0    Good
Name: Diet_Quality, dtype: object
- Alcohol Consumption Mode: 0    Moderate
Name: Alcohol_Consumption, dtype: object
Percentage Distribution of Each Factor:
Physical Activity Distribution: Physical_Activity
Moderate    41.093117
High        30.263158
Low         28.643725
Name: proportion, dtype: float64
Diet Quality Distribution: Diet_Quality
Good       40.856950
Average    39.777328
Poor       19.365722
Name: proportion, dtype: float64
Alcohol Consumption Distribution: Alcohol_Consumption
Moderate    43.212670
Low         34.728507
High        22.058824
Name: proportion, dtype: float64

### Function / Example Usage

In [79]:
def analyze_heart_attack_lifestyle(data2):
    heart_attack = data2[data2["Heart_Attack_Occurrence"] == "Yes"]

    #finding mode
    physical_activity_mode = heart_attack["Physical_Activity"].mode()
    diet_quality_mode = heart_attack["Diet_Quality"].mode()
    alcohol_consumption_mode = heart_attack["Alcohol_Consumption"].mode()

    # Extract the first mode value (the most common lifestyle)
    physical_activity_mode = physical_activity_mode[0]
    diet_quality_mode = diet_quality_mode[0]
    alcohol_consumption_mode = alcohol_consumption_mode[0]

    # Computing the proportion of each category
    physical_activity_dist = heart_attack["Physical_Activity"].value_counts(normalize=True) * 100
    diet_quality_dist = heart_attack["Diet_Quality"].value_counts(normalize=True) * 100
    alcohol_consumption_dist = heart_attack["Alcohol_Consumption"].value_counts(normalize=True) * 100

    print("Most Common Lifestyle Factors for Individuals Who Had a Heart Attack:")
    print("- Physical Activity Mode:", physical_activity_mode)
    print("- Diet Quality Mode:", diet_quality_mode)
    print("- Alcohol Consumption Mode:", alcohol_consumption_mode)

    print("Percentage Distribution of Each Factor:")
    print("Physical Activity Distribution:", physical_activity_dist)
    print("Diet Quality Distribution:", diet_quality_dist)
    print("Alcohol Consumption Distribution:", alcohol_consumption_dist)

#### Example Usage

In [80]:
analyze_heart_attack_lifestyle(data2)

Most Common Lifestyle Factors for Individuals Who Had a Heart Attack:
- Physical Activity Mode: Moderate
- Diet Quality Mode: Good
- Alcohol Consumption Mode: Moderate
Percentage Distribution of Each Factor:
Physical Activity Distribution: Physical_Activity
Moderate    41.093117
High        30.263158
Low         28.643725
Name: proportion, dtype: float64
Diet Quality Distribution: Diet_Quality
Good       40.856950
Average    39.777328
Poor       19.365722
Name: proportion, dtype: float64
Alcohol Consumption Distribution: Alcohol_Consumption
Moderate    43.212670
Low         34.728507
High        22.058824
Name: proportion, dtype: float64

## Dataset 2: MLB Hitters Data

In [94]:
second_data = pd.read_csv("mlbhitters.csv")
second_data.head(10)

,id,rank,year,player,batted_ball_events,launch_angle,sweet_spot_percentage,max_ev,average_ev,fly_ball_line_drive_ev,ground_ball_ev,max_distance,average_distance,average_homerun,hard_hit_95mph+,hard_hit_percentage,hard_hit_swing_percentage,total_barrels,barrels_batted_balls_percentage,barrels_plate_appearance_percentage
0,1,1,2022,"Judge, Aaron",341,14.6,37.8,118.4,95.8,100.2,89.1,465,205,413.0,210,61.6,20.3,91,26.7,15.8
1,2,2,2022,"Alvarez, Yordan",304,12.1,40.1,117.4,95.5,98.2,92.7,469,193,403.0,186,61.2,23.7,59,19.4,12.7
2,3,3,2022,"Trout, Mike",234,24.7,37.2,114.4,91.7,94.9,87.7,472,218,407.0,120,51.3,16.5,46,19.7,11.6
3,4,4,2022,"Schwarber, Kyle",312,18.9,34.6,114.8,93.3,99.7,87.2,468,197,415.0,170,54.5,17.6,64,20.5,11.5
4,5,5,2022,"Stanton, Giancarlo",228,10.2,26.3,119.8,94.6,98.2,94.1,445,160,400.0,117,51.3,17.8,42,18.4,11.3
5,6,6,2022,"Ohtani, Shohei",354,12.6,34.7,119.1,92.6,97.2,87.7,462,180,408.0,168,47.5,16.2,62,17.5,11.1
6,7,7,2022,"Riley, Austin",386,13.9,39.1,115.9,92.8,97.7,87.5,441,190,411.0,202,52.3,17.4,64,16.6,10.9
7,8,8,2022,"Pederson, Joc",241,14.6,34.0,112.8,93.3,96.4,91.2,441,191,410.0,130,54.2,20.0,38,15.8,10.6
8,9,9,2022,"Buxton, Byron",225,21.4,34.2,113.5,92.9,97.4,88.3,469,194,410.0,113,50.2,15.8,37,16.4,9.7
9,10,10,2022,"Mountcastle, Ryan",350,15.7,38.6,112.0,91.1,94.4,87.8,437,186,408.0,161,46.0,14.3,49,14.0,9.6

### Question Number 1: 
When we look at the top 5 players and the bottom 5 players (determined by the rank), how they do compare in terms of the difference between max exit velocity and average velocity? * In baseball, a small difference between max and average velocity is desired because it means a player is consistent.

### Pseudocode
1. Extract the top 5 players and the bottom 5 players.
2. Calculate the difference between max velocity and average velocity for each player. 
3. Calculate the average difference for two groups: top 5 and bottom 5
4. Compare the two numbers

### Single Line

In [98]:
# Extracting the top 5 players and the bottom 5 players
top5 = second_data.head(5)
bottom5 = second_data.tail(5)

In [101]:
# Calculaing the difference between max velocity and average velocity for each player

top5["velocity_diff"] = top5["max_ev"] - top5["average_ev"]
bottom5["velocity_diff"] = bottom5["max_ev"] - bottom5["average_ev"]

/tmp/ipykernel_1791/3749043045.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top5["velocity_diff"] = top5["max_ev"] - top5["average_ev"]
/tmp/ipykernel_1791/3749043045.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bottom5["velocity_diff"] = bottom5["max_ev"] - bottom5["average_ev"]

In [102]:
# Calculating the average difference for the two groups
top5_avg_diff = top5["velocity_diff"].mean()
bottom5_avg_diff = bottom5["velocity_diff"].mean()

In [140]:
# Returning the results for comparison (result shows that top 5 players are more consistent in terms of exit velocity)

print(f"Top 5 Players - Avg Velocity Difference: {top5_avg_diff}")
print(f"Bottom 5 Players - Avg Velocity Difference: {bottom5_avg_diff}")

Top 5 Players - Avg Velocity Difference: 22.780000000000005
Bottom 5 Players - Avg Velocity Difference: 23.660000000000004

### Function / Example Usage

In [147]:
def average_velo_diff (data):
    top5 = data.head(5)
    bottom5 = data.tail(5)

    # Calculateing the velocity difference
    top5["velocity_diff"] = top5["max_ev"] - top5["average_ev"]
    bottom5["velocity_diff"] = bottom5["max_ev"] - bottom5["average_ev"]

    # Calculating the average difference
    top5_avg_diff = top5["velocity_diff"].mean()
    bottom5_avg_diff = bottom5["velocity_diff"].mean()

    # Printing results for comparison
    if top5_avg_diff > bottom5_avg_diff:
        print("Top 5 Players are more inconsistent in terms of exit velocity")
    else:
        print("Top 5 Players are more consistent in terms of exit velocity")

#### Example Usage

In [148]:
average_velo_diff(second_data)

Top 5 Players are more consistent in terms of exit velocity

/tmp/ipykernel_1791/1760246945.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top5["velocity_diff"] = top5["max_ev"] - top5["average_ev"]
/tmp/ipykernel_1791/1760246945.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bottom5["velocity_diff"] = bottom5["max_ev"] - bottom5["average_ev"]

### Question Number 2:
Is there a relationship between the number of batted ball events (times a player made contact) and the number of hard-hit balls (95+ mph exit velocity)?

### Pseudocode
1. Group the data by player
2. Aggregate the hard-hit counts per player
3. Create a data frame combining batted ball events and hard-hit counts
4. Compute the correlation between batted ball events and hard-hit balls
5. Print the correlation value and interpret the result

### Single Line

In [129]:
# Grouping by player and taking the maximum batted ball events per player
player_batted_ball = second_data.groupby("player")["batted_ball_events"].max()
print(player_batted_ball)

player
Abreu, José          508
Acuña Jr., Ronald    439
Adames, Willy        382
Adams, Matt          255
Adell, Jo             69
                    ...
Zimmer, Bradley      181
Zimmerman, Ryan      403
Zobrist, Ben         449
Zunino, Mike         228
d'Arnaud, Travis     292
Name: batted_ball_events, Length: 596, dtype: int64

In [130]:
# Aggregating the hard-hit counts per player
player_hard_hit_95 = second_data.groupby("player")["hard_hit_95mph+"].sum()

In [131]:
# Creating a DataFrame combining batted ball events and hard-hit counts
player_stats = pd.DataFrame({
    "batted_ball_events": player_batted_ball, 
    "hard_hit_95+": player_hard_hit_95
})

# Filling missing values with 0 in case some players have no hard-hit balls
player_stats = player_stats.fillna(0)

In [134]:
# Computing the correlation
correlation_bbe_hh95 = player_stats["batted_ball_events"].corr(player_stats["hard_hit_95+"])
print(f"Correlation between Batted Ball Events and Hard-Hit Balls (95+ mph): {correlation_bbe_hh95}")

Correlation between Batted Ball Events and Hard-Hit Balls (95+ mph): 0.7081152476353377

In [135]:
# Interpretation
if abs(correlation_bbe_hh95) > 0.5:
    print("There is a strong relationship between total batted ball events and hard-hit balls.")
elif abs(correlation_bbe_hh95) > 0.2:
    print("There is a weak relationship between total batted ball events and hard-hit balls.")
else:
    print("There is little to no relationship between total batted ball events and hard-hit balls.")

There is a strong relationship between total batted ball events and hard-hit balls.

### Function / Example Usage

In [143]:
def cor_bbe_hardhits (data):
    # Grouping by player and taking the maximum batted ball events per player
    player_batted_ball = second_data.groupby("player")["batted_ball_events"].max()

    # Aggregating the hard-hit counts per player
    player_hard_hit_95 = second_data.groupby("player")["hard_hit_95mph+"].sum()

    # Creating a DataFrame combining batted ball events and hard-hit counts
    player_stats = pd.DataFrame({
    "batted_ball_events": player_batted_ball, 
    "hard_hit_95+": player_hard_hit_95})
    
    # Filling missing values with 0 in case some players have no hard-hit balls
    player_stats = player_stats.fillna(0)
    correlation_bbe_hh95 = player_stats["batted_ball_events"].corr(player_stats["hard_hit_95+"])
    
    # Interpretation
    if abs(correlation_bbe_hh95) > 0.5:
        print("There is a strong relationship between total batted ball events and hard-hit balls.")
    elif abs(correlation_bbe_hh95) > 0.2:
        print("There is a weak relationship between total batted ball events and hard-hit balls.")
    else:
        print("There is little to no relationship between total batted ball events and hard-hit balls.")

#### Example Usage

In [144]:
cor_bbe_hardhits(second_data)

There is a strong relationship between total batted ball events and hard-hit balls.